language: python
python:
  - "2.7"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install mock
  - pip install coveralls
  - pip install .

script:
  nosetests --with-coverage --cover-package=algorithm_logger

after_success:
  coveralls